//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHocSinh
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLHSEntities : DbContext
    {
        public QLHSEntities()
            : base("name=QLHSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Class> Classes { get; set; }
        public DbSet<ClassLevel> ClassLevels { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Point> Points { get; set; }
        public DbSet<RuleAge> RuleAges { get; set; }
        public DbSet<RuleStandardScore> RuleStandardScores { get; set; }
        public DbSet<RuleSubject> RuleSubjects { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
